const fs = require('fs');
const path = require('path');

const SKILLS_DIR = path.join(__dirname, 'skills');
const IND_DIR = path.join(SKILLS_DIR, 'industries');
const GOALS_DIR = path.join(SKILLS_DIR, 'goals');
const PAGES_DIR = path.join(SKILLS_DIR, 'pageTypes');

// Ensure dirs
[IND_DIR, GOALS_DIR, PAGES_DIR].forEach(d => {
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
});

/* -------------------------------------------------------------------------- */
/* 1. INDUSTRIES (19 files)                                                   */
/* -------------------------------------------------------------------------- */
const industries = [
  { id: 'agency', name: 'Agency / Marketing', focus: 'results, ROI, creative strategy' },
  { id: 'saas', name: 'SaaS / Tech', focus: 'scalability, innovation, workflow automation' },
  { id: 'real_estate', name: 'Real Estate', focus: 'luxury, prime locations, lifestyle' },
  { id: 'restaurant', name: 'Restaurant / Food', focus: 'flavor, ambiance, fresh ingredients' },
  { id: 'ecommerce', name: 'E-commerce', focus: 'conversion, fast shipping, premium quality' },
  { id: 'medical', name: 'Medical / Health', focus: 'compassion, expertise, advanced care' },
  { id: 'legal', name: 'Law Firm / Legal', focus: 'trust, aggressive representation, protection' },
  { id: 'finance', name: 'Accounting / Finance', focus: 'growth, security, numbers-driven' },
  { id: 'construction', name: 'Construction / Contractor', focus: 'durability, timeline, craftsmanship' },
  { id: 'home_services', name: 'Home Services', focus: 'reliability, timely service, neatness' },
  { id: 'consulting', name: 'Consulting', focus: 'strategic edge, efficiency, market dominance' },
  { id: 'nonprofit', name: 'Non-Profit', focus: 'impact, community, mission-driven' },
  { id: 'event_planning', name: 'Event Planning', focus: 'memorable experiences, flawless execution' },
  { id: 'photography', name: 'Photography / Creative', focus: 'capturing moments, artistic vision' },
  { id: 'logistics', name: 'Logistics / Shipping', focus: 'speed, global reach, tracking' },
  { id: 'education', name: 'Education / Coaching', focus: 'growth, learning, unlocking potential' },
  { id: 'fitness', name: 'Fitness / Gym', focus: 'endurance, strength, transformation' },
  { id: 'automotive', name: 'Automotive', focus: 'performance, reliability, sleek design' },
  { id: 'beauty', name: 'Beauty / Salon', focus: 'pampering, style, self-care' }
];

industries.forEach(ind => {
  const content = `## INDUSTRY CONTEXT: ${ind.name}
You are writing copy for a ${ind.name} business.
Focus heavily on: ${ind.focus}.
Use terminology tailored to this industry. Avoid generic business jargon.
When generating images, use Unsplash keywords like: ${ind.name.split('/')[0].toLowerCase().trim()}.`;
  fs.writeFileSync(path.join(IND_DIR, `${ind.id}.md`), content);
});


/* -------------------------------------------------------------------------- */
/* 2. GOALS (22 files)                                                        */
/* -------------------------------------------------------------------------- */
const goals = [
  'Generate Leads', 'Sell Products', 'Book Appointments', 'Brand Awareness',
  'Promote an Event', 'Showcase Portfolio', 'Build Email List', 'Share Information',
  'Provide Customer Support', 'Recruit Employees', 'Educate Audience', 'Drive App Downloads',
  'Collect Donations', 'Build Community', 'Announce a Launch', 'Offer a Free Trial',
  'Register for Webinar', 'Run a Contest', 'Highlight Case Studies', 'Request a Quote',
  'Schedule a Demo', 'Provide FAQs'
];

goals.forEach(goal => {
  const filename = goal.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const content = `## PAGE GOAL: ${goal}
This page is entirely optimized for: ${goal}.
All Call-to-Action (CTA) buttons must relentlessly drive users toward this exact outcome.
Headings should address the user's desire to ${goal.toLowerCase()}.
Limit distractions—everything on this page serves this primary goal.`;
  fs.writeFileSync(path.join(GOALS_DIR, `${filename}.md`), content);
});


/* -------------------------------------------------------------------------- */
/* 3. PAGE TYPES (12 files) — defining the exact JSON object schema keys      */
/* -------------------------------------------------------------------------- */
const pageTypes = {
  'homepage': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short punchy tagline under 8 words",
    "EYEBROW": "3-5 word uppercase label e.g. DUBAI'S #1 SEO AGENCY",
    "NAV_CTA": "short nav button text e.g. Get Started",
    "HERO_H1_LINE1": "first line of hero headline (3-5 words)",
    "HERO_H1_LINE2": "second line, the most powerful words (2-4 words)",
    "HERO_BODY": "1-2 sentence hero description, specific and compelling",
    "HERO_CTA_1": "primary button text",
    "HERO_CTA_2": "secondary button text",
    "HERO_IMAGE_URL": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=1200&q=85",
    "LOGOSTRIP_LABEL": "Trusted by line e.g. Trusted by 200+ businesses across the UAE",
    "LOGO_1": "Client or partner name 1",
    "LOGO_2": "Client or partner name 2",
    "LOGO_3": "Client or partner name 3",
    "LOGO_4": "Client or partner name 4",
    "LOGO_5": "Client or partner name 5",
    "SERVICES_EYEBROW": "WHAT WE DO",
    "SERVICES_H2": "Services section heading",
    "SERVICES_BODY": "1 sentence about services",
    "SERVICES_CTA": "View All Services",
    "SERVICE_1_TITLE": "Service 1 name",
    "SERVICE_1_DESC": "2-3 sentence description",
    "SERVICE_1_ICON": "emoji",
    "SERVICE_2_TITLE": "Service 2 name",
    "SERVICE_2_DESC": "2-3 sentence description",
    "SERVICE_2_ICON": "emoji",
    "SERVICE_3_TITLE": "Service 3 name",
    "SERVICE_3_DESC": "2-3 sentence description",
    "SERVICE_3_ICON": "emoji",
    "ABOUT_EYEBROW": "OUR STORY",
    "ABOUT_H2_LINE1": "first part of about heading",
    "ABOUT_H2_LINE2": "italic second part",
    "ABOUT_BODY": "2-3 sentence about paragraph",
    "ABOUT_IMAGE_URL": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=1200&q=85",
    "ABOUT_CHECK_1": "Key differentiator 1",
    "ABOUT_CHECK_2": "Key differentiator 2",
    "ABOUT_CHECK_3": "Key differentiator 3",
    "ABOUT_CTA": "Learn More About Us",
    "STAT_1_NUM": "number with suffix e.g. 200+",
    "STAT_1_LABEL": "what that number means",
    "STAT_2_NUM": "number",
    "STAT_2_LABEL": "what it means",
    "STAT_3_NUM": "number",
    "STAT_3_LABEL": "what it means",
    "STAT_4_NUM": "number",
    "STAT_4_LABEL": "what it means",
    "TESTI_EYEBROW": "WHAT OUR CLIENTS SAY",
    "TESTI_H2": "Testimonials heading",
    "TESTI_1_QUOTE": "Client quote 2-3 sentences",
    "TESTI_1_NAME": "Client Name",
    "TESTI_1_ROLE": "Title, Company",
    "TESTI_2_QUOTE": "Client quote 2",
    "TESTI_2_NAME": "Client Name 2",
    "TESTI_2_ROLE": "Title, Company 2",
    "TESTI_3_QUOTE": "Client quote 3",
    "TESTI_3_NAME": "Client Name 3",
    "TESTI_3_ROLE": "Title, Company 3",
    "CTA_EYEBROW": "READY TO GET STARTED?",
    "CTA_H2_LINE1": "CTA heading",
    "CTA_H2_LINE2": "CTA heading part 2",
    "CTA_BODY": "1-2 sentence CTA description",
    "CTA_BTN_1": "Primary CTA",
    "CTA_BTN_2": "Secondary CTA",
    "FOOTER_TAGLINE": "Short brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'about-us': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short punchy tagline",
    "NAV_CTA": "Get Started",
    "HEADER_H1": "About Us",
    "HEADER_BREADCRUMBS": "Home / About Us",
    "STORY_EYEBROW": "OUR JOURNEY",
    "STORY_H2": "How We Started",
    "STORY_P1": "Paragraph 1 of company history",
    "STORY_P2": "Paragraph 2 defining the turning point",
    "STORY_IMAGE_URL": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=1200&q=85",
    "MISSION_EYEBROW": "OUR MISSION",
    "MISSION_H2": "What drives us forward",
    "MISSION_BODY": "1 paragraph mission statement",
    "VISION_EYEBROW": "OUR VISION",
    "VISION_H2": "Where we are going",
    "VISION_BODY": "1 paragraph vision statement",
    "VALUES_EYEBROW": "CORE VALUES",
    "VALUES_H2": "The principles we stand by",
    "VAL_1_ICON": "emoji",
    "VAL_1_TITLE": "Value 1",
    "VAL_1_DESC": "Short description",
    "VAL_2_ICON": "emoji",
    "VAL_2_TITLE": "Value 2",
    "VAL_2_DESC": "Short description",
    "VAL_3_ICON": "emoji",
    "VAL_3_TITLE": "Value 3",
    "VAL_3_DESC": "Short description",
    "VAL_4_ICON": "emoji",
    "VAL_4_TITLE": "Value 4",
    "VAL_4_DESC": "Short description",
    "TEAM_EYEBROW": "LEADERSHIP",
    "TEAM_H2": "Meet the team",
    "TEAM_1_IMG": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=85",
    "TEAM_1_NAME": "Name 1",
    "TEAM_1_ROLE": "CEO & Founder",
    "TEAM_2_IMG": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=85",
    "TEAM_2_NAME": "Name 2",
    "TEAM_2_ROLE": "Head of Operations",
    "TEAM_3_IMG": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=85",
    "TEAM_3_NAME": "Name 3",
    "TEAM_3_ROLE": "Lead Engineer",
    "CTA_EYEBROW": "WORK WITH US",
    "CTA_H2_LINE1": "Join our journey",
    "CTA_H2_LINE2": "and grow with us",
    "CTA_BODY": "CTA text",
    "CTA_BTN_1": "Contact Us",
    "CTA_BTN_2": "View Services",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'services': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short punchy tagline",
    "NAV_CTA": "Get Started",
    "HEADER_H1": "Our Services",
    "HEADER_BREADCRUMBS": "Home / Services",
    "INTRO_EYEBROW": "WHAT WE OFFER",
    "INTRO_H2": "Comprehensive solutions for your business",
    "INTRO_BODY": "1-2 sentence introduction paragraph",
    "SRV_1_EYEBROW": "SERVICE 01",
    "SRV_1_H2": "First Service Name",
    "SRV_1_P1": "Paragraph detailing service 1",
    "SRV_1_LI1": "Benefit bullet 1",
    "SRV_1_LI2": "Benefit bullet 2",
    "SRV_1_LI3": "Benefit bullet 3",
    "SRV_1_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "SRV_2_EYEBROW": "SERVICE 02",
    "SRV_2_H2": "Second Service Name",
    "SRV_2_P1": "Paragraph detailing service 2",
    "SRV_2_LI1": "Benefit bullet 1",
    "SRV_2_LI2": "Benefit bullet 2",
    "SRV_2_LI3": "Benefit bullet 3",
    "SRV_2_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "SRV_3_EYEBROW": "SERVICE 03",
    "SRV_3_H2": "Third Service Name",
    "SRV_3_P1": "Paragraph detailing service 3",
    "SRV_3_LI1": "Benefit bullet 1",
    "SRV_3_LI2": "Benefit bullet 2",
    "SRV_3_LI3": "Benefit bullet 3",
    "SRV_3_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROC_EYEBROW": "HOW IT WORKS",
    "PROC_H2": "Our Proven Process",
    "PROC_1_TITLE": "Step 1: Discovery",
    "PROC_1_DESC": "Description of step 1",
    "PROC_2_TITLE": "Step 2: Strategy",
    "PROC_2_DESC": "Description of step 2",
    "PROC_3_TITLE": "Step 3: Execution",
    "PROC_3_DESC": "Description of step 3",
    "PROC_4_TITLE": "Step 4: Delivery",
    "PROC_4_DESC": "Description of step 4",
    "CTA_EYEBROW": "LET'S TALK",
    "CTA_H2_LINE1": "Ready to scale?",
    "CTA_H2_LINE2": "Get in touch today",
    "CTA_BODY": "CTA description",
    "CTA_BTN_1": "Request a Quote",
    "CTA_BTN_2": "Call Us Now",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'contact-us': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short tagline",
    "NAV_CTA": "Get Started",
    "HEADER_H1": "Contact Us",
    "HEADER_BREADCRUMBS": "Home / Contact Us",
    "CONTACT_EYEBROW": "GET IN TOUCH",
    "CONTACT_H2": "We'd love to hear from you",
    "CONTACT_BODY": "Reach out to our team directly or fill out the form below.",
    "INFO_1_TITLE": "Email Us",
    "INFO_1_DESC": "Drop us a line anytime",
    "INFO_1_VAL": "${email || 'contact@company.com'}",
    "INFO_2_TITLE": "Call Us",
    "INFO_2_DESC": "Mon-Fri from 9am to 6pm",
    "INFO_2_VAL": "${phone || '+971 50 000 0000'}",
    "INFO_3_TITLE": "Visit Us",
    "INFO_3_DESC": "Our headquarters",
    "INFO_3_VAL": "${location || 'Dubai, UAE'}",
    "FORM_H3": "Send us a message",
    "FORM_P": "We will get back to you within 24 hours.",
    "BTN_SUBMIT": "Send Message",
    "MAP_URL": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3610.178510024322!2d55.27411631500969!3d25.198939283894817!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f43348a67e24b%3A0xff45e502e1ceb7e2!2sBurj%20Khalifa!5e0!3m2!1sen!2sae!4v1620000000000!5m2!1sen!2sae",
    "FAQ_EYEBROW": "QUICK ANSWERS",
    "FAQ_H2": "Frequently Asked Questions",
    "FAQ_1_Q": "What are your business hours?",
    "FAQ_1_A": "We operate Monday through Friday, 9:00 AM to 6:00 PM.",
    "FAQ_2_Q": "How quickly do you respond?",
    "FAQ_2_A": "We aim to respond to all inquiries within 24 business hours.",
    "FAQ_3_Q": "Do you offer international services?",
    "FAQ_3_A": "Yes, we work with clients globally. Please mention your timezone.",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'offer-promo': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short punchy tagline",
    "HERO_EYEBROW": "LIMITED TIME OFFER",
    "HERO_H1_LINE1": "Exclusive Promo",
    "HERO_H1_LINE2": "Save up to 50%",
    "HERO_BODY": "Claim this highly exclusive offer before time runs out.",
    "HERO_CTA_1": "Claim Offer Now",
    "HERO_IMAGE_URL": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=1200&q=85",
    "BENEFIT_EYEBROW": "WHY CLAIM THIS?",
    "BENEFIT_H2": "Unlock massive value today",
    "BEN_1_TITLE": "Instant Access",
    "BEN_1_DESC": "Description here",
    "BEN_2_TITLE": "Premium Support",
    "BEN_2_DESC": "Description here",
    "BEN_3_TITLE": "Money-Back Guarantee",
    "BEN_3_DESC": "Description here",
    "TESTI_QUOTE": "This offer changed completely the way we operate. Maximum ROI.",
    "TESTI_NAME": "Client Name",
    "TESTI_ROLE": "CEO",
    "CTA_EYEBROW": "DON'T MISS OUT",
    "CTA_H2_LINE1": "Offer ends soon.",
    "CTA_H2_LINE2": "Act fast.",
    "CTA_BODY": "Join hundreds of others who have taken advantage.",
    "CTA_BTN_1": "Claim Offer Now",
    "FOOTER_TAGLINE": "Brand promise",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'portfolio': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short tagline",
    "NAV_CTA": "Get a Quote",
    "HEADER_H1": "Our Portfolio",
    "HEADER_BREADCRUMBS": "Home / Portfolio",
    "PORTFOLIO_EYEBROW": "OUR WORK",
    "PORTFOLIO_H2": "Featured Projects",
    "PORTFOLIO_BODY": "Explore some of our finest work across various industries.",
    "CAT_1": "All",
    "CAT_2": "Commercial",
    "CAT_3": "Residential",
    "CAT_4": "Industrial",
    "PROJ_1_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROJ_1_TITLE": "Project Name 1",
    "PROJ_1_CAT": "Commercial",
    "PROJ_2_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROJ_2_TITLE": "Project Name 2",
    "PROJ_2_CAT": "Residential",
    "PROJ_3_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROJ_3_TITLE": "Project Name 3",
    "PROJ_3_CAT": "Industrial",
    "PROJ_4_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROJ_4_TITLE": "Project Name 4",
    "PROJ_4_CAT": "Commercial",
    "PROJ_5_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROJ_5_TITLE": "Project Name 5",
    "PROJ_5_CAT": "Residential",
    "PROJ_6_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=800&q=85",
    "PROJ_6_TITLE": "Project Name 6",
    "PROJ_6_CAT": "Industrial",
    "CTA_EYEBROW": "START YOUR PROJECT",
    "CTA_H2_LINE1": "Ready to build",
    "CTA_H2_LINE2": "something amazing?",
    "CTA_BODY": "Let's discuss how we can bring your vision to life.",
    "CTA_BTN_1": "Contact Us",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'pricing': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short tagline",
    "NAV_CTA": "Get Started",
    "HEADER_H1": "Pricing Plans",
    "HEADER_BREADCRUMBS": "Home / Pricing",
    "PRICING_EYEBROW": "PLANS FOR EVERYONE",
    "PRICING_H2": "Simple, transparent pricing",
    "PRICING_BODY": "No hidden fees or surprise charges. Select what works for you.",
    "TIER_1_NAME": "Starter",
    "TIER_1_PRICE": "$99",
    "TIER_1_PERIOD": "/month",
    "TIER_1_DESC": "Perfect for small businesses.",
    "TIER_1_FEAT_1": "Feature list item 1",
    "TIER_1_FEAT_2": "Feature list item 2",
    "TIER_1_FEAT_3": "Feature list item 3",
    "TIER_1_BTN": "Start Free Trial",
    "TIER_2_NAME": "Professional",
    "TIER_2_PRICE": "$299",
    "TIER_2_PERIOD": "/month",
    "TIER_2_DESC": "Ideal for growing teams.",
    "TIER_2_FEAT_1": "Everything in Starter",
    "TIER_2_FEAT_2": "Advanced reporting",
    "TIER_2_FEAT_3": "Priority support",
    "TIER_2_BTN": "Get Professional",
    "TIER_3_NAME": "Enterprise",
    "TIER_3_PRICE": "Custom",
    "TIER_3_PERIOD": "",
    "TIER_3_DESC": "For large organizations.",
    "TIER_3_FEAT_1": "Everything in Pro",
    "TIER_3_FEAT_2": "Dedicated account manager",
    "TIER_3_FEAT_3": "Custom integrations",
    "TIER_3_BTN": "Contact Sales",
    "FAQ_EYEBROW": "PRICING FAQS",
    "FAQ_H2": "Got questions?",
    "FAQ_1_Q": "Can I cancel anytime?",
    "FAQ_1_A": "Yes, there are no long-term contracts.",
    "FAQ_2_Q": "Are there setup fees?",
    "FAQ_2_A": "No, all our plans include free setup.",
    "FAQ_3_Q": "Do you offer refunds?",
    "FAQ_3_A": "Yes, within the first 14 days of your purchase.",
    "CTA_EYEBROW": "NOT SURE?",
    "CTA_H2_LINE1": "Need a custom",
    "CTA_H2_LINE2": "enterprise plan?",
    "CTA_BODY": "Contact our sales team today.",
    "CTA_BTN_1": "Contact Sales",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'testimonials': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "tagline",
    "NAV_CTA": "Get Started",
    "HEADER_H1": "Client Testimonials",
    "HEADER_BREADCRUMBS": "Home / Reviews",
    "TESTI_EYEBROW": "OUR REPUTATION",
    "TESTI_H2": "Don't just take our word for it",
    "TESTI_BODY": "Hear what our amazing clients have to say about working with us.",
    "T_1_QUOTE": "Exceptional service from start to finish.",
    "T_1_NAME": "John Doe",
    "T_1_ROLE": "CEO",
    "T_2_QUOTE": "They delivered exactly what they promised.",
    "T_2_NAME": "Jane Smith",
    "T_2_ROLE": "Founder",
    "T_3_QUOTE": "Highly recommended team.",
    "T_3_NAME": "Mark Wilson",
    "T_3_ROLE": "Director",
    "T_4_QUOTE": "Best investment we made this year.",
    "T_4_NAME": "Sarah Lee",
    "T_4_ROLE": "Marketing Lead",
    "T_5_QUOTE": "Our profits doubled after using them.",
    "T_5_NAME": "Mike Boss",
    "T_5_ROLE": "Owner",
    "T_6_QUOTE": "Incredible attention to detail.",
    "T_6_NAME": "Emma Frost",
    "T_6_ROLE": "Consultant",
    "CTA_EYEBROW": "BECOME OUR NEXT SUCCESS",
    "CTA_H2_LINE1": "Ready to get",
    "CTA_H2_LINE2": "started?",
    "CTA_BODY": "Join these happy clients today.",
    "CTA_BTN_1": "Contact Us",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'team': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "tagline",
    "NAV_CTA": "Join Us",
    "HEADER_H1": "Our Team",
    "HEADER_BREADCRUMBS": "Home / Team",
    "LEADER_EYEBROW": "A MESSAGE FROM THE FOUNDER",
    "LEADER_H2": "Building a culture of excellence",
    "LEADER_P1": "Letter paragraph 1",
    "LEADER_P2": "Letter paragraph 2",
    "LEADER_NAME": "Founder Name",
    "LEADER_ROLE": "Founder & CEO",
    "LEADER_IMG": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&q=85",
    "TEAM_EYEBROW": "THE EXPERTS",
    "TEAM_H2": "Meet the minds behind the magic",
    "M1_NAME": "Name 1", "M1_ROLE": "Role 1", "M1_IMG": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=85",
    "M2_NAME": "Name 2", "M2_ROLE": "Role 2", "M2_IMG": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=85",
    "M3_NAME": "Name 3", "M3_ROLE": "Role 3", "M3_IMG": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=85",
    "M4_NAME": "Name 4", "M4_ROLE": "Role 4", "M4_IMG": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=85",
    "CTA_EYEBROW": "CAREERS",
    "CTA_H2_LINE1": "We are currently",
    "CTA_H2_LINE2": "hiring!",
    "CTA_BODY": "Check out our open positions.",
    "CTA_BTN_1": "View Openings",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'faq': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "tagline",
    "NAV_CTA": "Support",
    "HEADER_H1": "Help & FAQs",
    "HEADER_BREADCRUMBS": "Home / FAQ",
    "FAQ_EYEBROW": "FIND ANSWERS",
    "FAQ_H2": "How can we help you?",
    "FAQ_BODY": "Browse our most frequently asked questions below.",
    "Q1": "Question 1", "A1": "Answer 1",
    "Q2": "Question 2", "A2": "Answer 2",
    "Q3": "Question 3", "A3": "Answer 3",
    "Q4": "Question 4", "A4": "Answer 4",
    "Q5": "Question 5", "A5": "Answer 5",
    "Q6": "Question 6", "A6": "Answer 6",
    "CTA_EYEBROW": "STILL STUCK?",
    "CTA_H2_LINE1": "Can't find what",
    "CTA_H2_LINE2": "you're looking for?",
    "CTA_BODY": "Reach out to our support team.",
    "CTA_BTN_1": "Contact Support",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },

  'blog': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "tagline",
    "NAV_CTA": "Subscribe",
    "HEADER_H1": "Insights & News",
    "HEADER_BREADCRUMBS": "Home / Blog",
    "FEAT_EYEBROW": "FEATURED ARTICLE",
    "FEAT_H2": "The Future of Our Industry in 2026",
    "FEAT_EXCERPT": "A deep dive into the trends shaping the upcoming year.",
    "FEAT_DATE": "March 2026",
    "FEAT_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=1200&q=85",
    "GRID_EYEBROW": "LATEST POSTS",
    "GRID_H2": "Read more from our team",
    "P1_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=600&q=85", "P1_TITLE": "Article 1 Title", "P1_DATE": "Feb 2026", "P1_CAT": "Insights",
    "P2_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=600&q=85", "P2_TITLE": "Article 2 Title", "P2_DATE": "Jan 2026", "P2_CAT": "News",
    "P3_IMG": "https://images.unsplash.com/photo-[RELEVANT_ID]?w=600&q=85", "P3_TITLE": "Article 3 Title", "P3_DATE": "Dec 2025", "P3_CAT": "Guides",
    "CTA_EYEBROW": "STAY UPDATED",
    "CTA_H2_LINE1": "Join our",
    "CTA_H2_LINE2": "newsletter",
    "CTA_BODY": "Get the latest insights delivered to your inbox.",
    "CTA_BTN_1": "Subscribe Now",
    "FOOTER_TAGLINE": "Brand promise",
    "PHONE": "${phone || '+971 50 000 0000'}",
    "EMAIL": "${email || 'hello@business.com'}",
    "LOCATION": "${location || 'Dubai, UAE'}",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  },
  
  'coming-soon': {
    "BUSINESS_NAME": "business name",
    "TAGLINE": "short punchy tagline",
    "HERO_EYEBROW": "GET READY",
    "HERO_H1_LINE1": "Something amazing",
    "HERO_H1_LINE2": "is coming soon",
    "HERO_BODY": "We are currently working hard building something extraordinary.",
    "HERO_CTA_1": "Notify Me",
    "FOOTER_TAGLINE": "Brand promise",
    "COPYRIGHT": "© 2026 ${businessName}. All rights reserved.",
    "PRIMARY_COLOR": "${primaryColor || '#00a86b'}"
  }
};

Object.entries(pageTypes).forEach(([type, schema]) => {
  fs.writeFileSync(path.join(PAGES_DIR, `${type}.json`), JSON.stringify(schema, null, 2));
});

console.log('Successfully generated all 53 files in skills/ !');
